#ifndef KHICAS_GB18030_H
#define KHICAS_GB18030_H

/*
 * Chinese (GB18030) text support for KhiCAS on fx-CG50.
 *
 * Chinese help strings are stored with a leading 0x01 marker byte followed by
 * GB18030 bytes (generated by tools/help-zh-gen.ps1 -> giacbf/static_helpzh.h).
 * The render layer must switch the OS character set to GB18030 around such
 * strings, otherwise they are drawn as garbage (or nothing). Strings without
 * the marker keep the default latin/multi-byte charset (which KhiCAS uses for
 * its own symbol glyphs, e.g. "\xE5\xEA" arrows), so they are never affected.
 *
 * The three functions below call the CASIOWIN syscalls directly (same recipe
 * as libfxcg asm.h) so the build does not depend on whether the libfxcg
 * snapshot shipped in casiolocal exposes EnableGB18030()/DisableGB18030().
 *
 * syscall ids: EnableGB18030=0x01E0  DisableGB18030=0x01DF  ProcessPrintChars=0x1300
 * dispatcher : 0x80020070 (CASIOWIN syscall entry)
 */

#ifdef __cplusplus
extern "C" {
#endif

void khicas_enable_gb18030(void);
void khicas_disable_gb18030(void);
int  khicas_process_print_chars(int charset);

#ifdef __cplusplus
}
#endif

/* Strip the 0x01 GB18030 marker. Returns 1 and sets *out to the text after the
 * marker when present; returns 0 and sets *out = s otherwise. */
static inline int khicas_gb_strip(const char * s, const char ** out) {
  if (s && (unsigned char)s[0] == 0x01) { *out = s + 1; return 1; }
  *out = s;
  return 0;
}

#endif /* KHICAS_GB18030_H */
