# ui-zh-gen.ps1 - generate giacbf/zhui.cc and rewrite UI ternaries into zhui(...)
#
# 1. Reads tools/ui-zh.json (English -> Chinese).
# 2. Emits giacbf/zhui.cc: a lookup table (Chinese = GB18030 bytes + 0x01 marker).
# 3. Rewrites  lang ? "<fr>" : "<en>"  (and (lang==1)?... variants) into
#    zhui("<en>", "<fr>")  -- but only when "<en>" is in the table, so
#    untranslated strings keep their exact behaviour.
#
# ASCII-only script body (PS 5.1 reads scripts as ANSI). File IO is explicit.
$ErrorActionPreference = 'Stop'

$root = 'D:\GitHub\khicas-opt'
$jsonPath = "$root\tools\ui-zh.json"
$ccPath   = "$root\giacbf\khicas_zhui.cc"
$latin1 = [System.Text.Encoding]::GetEncoding(28591)

$jsonText = [System.IO.File]::ReadAllText($jsonPath, [System.Text.Encoding]::UTF8)
$table = $jsonText | ConvertFrom-Json

# PS string -> GB18030 bytes -> C literal with 0x01 marker
function To-MarkedGB18030([string]$text) {
    $enc = [System.Text.Encoding]::GetEncoding('GB18030')
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append('"')
    [void]$sb.Append('\x01')
    [void]$sb.Append('""')   # close+reopen: a following hex digit must not merge into the escape
    foreach ($ch in $text.ToCharArray()) {
        $cb = $enc.GetBytes([string]$ch)
        if ($cb.Length -gt 2) { $cb = @([byte][char]'?') }
        foreach ($b in $cb) {
            if ($b -ge 0x80) {
                [void]$sb.Append('""'); [void]$sb.Append('\x'); [void]$sb.Append($b.ToString('x2')); [void]$sb.Append('""')
            } elseif ($b -eq 0x22) { [void]$sb.Append('\"')
            } elseif ($b -eq 0x5C) { [void]$sb.Append('\\')
            } else { [void]$sb.Append([char]$b) }
        }
    }
    [void]$sb.Append('"')
    return $sb.ToString()
}

# plain C literal for the English key
function To-PlainCString([string]$text) {
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append('"')
    foreach ($ch in $text.ToCharArray()) {
        if ($ch -eq '"') { [void]$sb.Append('\"') }
        elseif ($ch -eq [char]0x5C) { [void]$sb.Append('\\') }
        elseif ([int]$ch -eq 10) { [void]$sb.Append('\n') }
        else { [void]$sb.Append($ch) }
    }
    [void]$sb.Append('"')
    return $sb.ToString()
}

# decode a C string literal (the english side) into a PS string for lookup
function Decode-CString([string]$lit) {
    $inner = $lit.Substring(1, $lit.Length - 2)
    $sb = New-Object System.Text.StringBuilder
    $i = 0
    while ($i -lt $inner.Length) {
        $ch = $inner[$i]
        if ($ch -eq [char]0x5C) {
            $nx = $inner[$i + 1]
            if ($nx -eq 'x') { [void]$sb.Append([char][Convert]::ToInt32($inner.Substring($i + 2, 2), 16)); $i += 4; continue }
            if ($nx -eq 'n') { [void]$sb.Append([char]10); $i += 2; continue }
            if ($nx -eq 't') { [void]$sb.Append([char]9); $i += 2; continue }
            [void]$sb.Append($nx); $i += 2; continue
        }
        [void]$sb.Append($ch); $i++
    }
    return $sb.ToString()
}

# --- 1. generate zhui.cc ---
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('/* Generated by tools/ui-zh-gen.ps1 - do not edit. */')
[void]$sb.AppendLine('#include "khicas_zhui.h"')
[void]$sb.AppendLine('#include "catalogGUI.hpp"   /* for lang */')
[void]$sb.AppendLine('#include <string.h>')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('struct zh_ui_entry { const char * en; const char * zh; };')
[void]$sb.AppendLine('static const zh_ui_entry zh_ui_table[] = {')
foreach ($p in $table.PSObject.Properties) {
    [void]$sb.AppendLine('  {' + (To-PlainCString $p.Name) + ', ' + (To-MarkedGB18030 $p.Value) + '},')
}
[void]$sb.AppendLine('};')
[void]$sb.AppendLine('static const int zh_ui_count = sizeof(zh_ui_table)/sizeof(zh_ui_entry);')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('const char * zhui(const char * en, const char * fr){')
[void]$sb.AppendLine('  if (zh_ui_enabled && en){')
[void]$sb.AppendLine('    for (int i=0;i<zh_ui_count;++i){')
[void]$sb.AppendLine('      if (!strcmp(en, zh_ui_table[i].en)) return zh_ui_table[i].zh;')
[void]$sb.AppendLine('    }')
[void]$sb.AppendLine('  }')
[void]$sb.AppendLine('  return lang ? fr : en;')
[void]$sb.AppendLine('}')
[System.IO.File]::WriteAllText($ccPath, $sb.ToString(), $latin1)
Write-Host ("zhui.cc: {0} entries" -f (($table.PSObject.Properties | Measure-Object).Count))

# --- 2. rewrite ternaries ---
$pat = '(?:(?:\(\s*lang\s*(?:==\s*1)?\s*\)|lang)\s*\?\s*)("(?:[^"\\]|\\.)*")\s*:\s*("(?:[^"\\]|\\.)*")'
$re = New-Object System.Text.RegularExpressions.Regex($pat)
$totalChanged = 0
foreach ($f in @('console.cc', 'textGUI.cpp', 'main.cc')) {
    $p = "$root\giacbf\$f"
    $txt = [System.IO.File]::ReadAllText($p, $latin1)
    $count = 0
    $new = $re.Replace($txt, {
        param($m)
        $frLit = $m.Groups[1].Value
        $enLit = $m.Groups[2].Value
        $en = Decode-CString $enLit
        $prop = $table.PSObject.Properties[$en]
        if ($prop -eq $null) { return $m.Value }
        # skip when the matched literal is part of a concatenation (a following
        # string literal) -- rewriting would leave the rest dangling
        $after = $m.Index + $m.Length
        while ($after -lt $txt.Length -and ($txt[$after] -eq ' ' -or $txt[$after] -eq "`t")) { $after++ }
        if ($after -lt $txt.Length -and $txt[$after] -eq '"') { return $m.Value }
        $script:count++
        return 'zhui(' + $enLit + ', ' + $frLit + ')'
    })
    if ($count -gt 0) {
        [System.IO.File]::WriteAllText($p, $new, $latin1)
    }
    Write-Host ("{0}: {1} ternaries -> zhui()" -f $f, $count)
    $totalChanged += $count
}
Write-Host "total rewritten: $totalChanged"
